---
name: Helm Chart

on:
  workflow_call:
    inputs:
      chart:
        description: Chart Name
        required: true
        type: string
      containerDigest:
        description: Container Image Digest
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release ${{ inputs.chart }}
    permissions:
      contents: write
    strategy:
      max-parallel: 4
      matrix:
        node-version: [ '16' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config --local user.email "${{ github.action }}+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch --tags
          git pull

      - name: Setup Helm
        uses: yokawasa/action-setup-kube-tools@v0.8.2
        with:
          setup-tools: |
            helm
      - name: Setup chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          install_only: true
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Container Image
        if: inputs.containerDigest != ''
        working-directory: charts/${{ inputs.chart }}
        run: |
          sed -i "/appVersion: .*'/appVersion: \"@${{ inputs.containerDigest }}\"/g" Chart.yaml
          git add Chart.yaml

      - name: Versioning and Changelog
        working-directory: charts/${{ inputs.chart }}
        run: |
          npx standard-version -i ../../release-CHANGELOG.md \
            --path ../../charts/** \
            --skip.commit \
            --skip.tag \
            --skip.bump
          npx standard-version \
            --path ../../charts/**
          TAG_NAME=`git describe --abbrev=0 --match "chart/${{ inputs.chart }}/v*"`
          echo "TAG_NAME=${TAG_NAME#"chart/${{ inputs.chart }}/"}" >> $GITHUB_ENV

      - name: Push Git Tag
        run: |
          git push --follow-tags

      - name: Create Helm Release
        run: |
          owner=$(cut -d '/' -f 1 <<< "${{ github.repository }}")
          repo=$(cut -d '/' -f 2 <<< "${{ github.repository }}")

          mkdir -p .cr-release-packages
          mkdir -p .cr-index
          
          cr package charts/${{ inputs.chart }} \
            --package-path .cr-release-packages

          cr upload \
            --owner "${owner}" \
            --git-repo "${repo}" \
            --commit "$(git rev-parse HEAD)" \
            --release-name-template "chart/{{ .Name }}/v{{ .Version }}" \
            --release-notes-file release-CHANGELOG.md \
            --package-path .cr-release-packages
          
          cr index \
            --owner "${owner}" \
            --git-repo "${repo}" \
            --release-name-template "chart/{{ .Name }}/v{{ .Version }}" \
            --push
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
